<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/11 0011
 * Time: 9:17
 */

namespace app\console;

//命令行核心
use think\console\Command;
//核心
use think\console\Input;
//核心
use think\console\Output;

use app\console\Common;
use \swoole\server;
use Predis\Client;
use think\Config;
use think\Controller;
use think\Db;
use think\Session;
use app\console\TB;

class WebSocket extends Common
{
    protected $server;

    //下方的异步定时器
    protected $time_id;

    //redis 连接
    protected $redis;

    protected $token;

    protected $all_user;

    protected $room;


    public function init()
    {
        $this->redis = new Client(Config::get('redis'));

    }


    //命令行配置函数
    protected function configure()
    {
        $this->setName('websocket:start')->setDescription('start Web Server Server!');
        //        parent::configure(); // TODO: Change the autogenerated stub
    }


    protected function execute(Input $input, Output $output)
    {


        $this->server = new \swoole_websocket_server('0.0.0.0', 9501);

        $this->server->set([
            'daemonize' => false,
            'max_request' => 2000,
        ]);

        //所有人表
        /**
         * $fd=>
         */

        $this->all_user = new \swoole_table(1048576); //2的100次方个
        $this->all_user->column('fd', \swoole_table::TYPE_INT, 8);
        $this->all_user->column('username', \swoole_table::TYPE_STRING, 32);
        $this->all_user->column('id', \swoole_table::TYPE_STRING, 16);
        $this->all_user->column('token', \swoole_table::TYPE_STRING, 64);
        $this->all_user->create();


        //所有的聊天室
        /**
         * $room_id=>[
         *          room_id=>room_id,
         *          admin_user=>admin_user
         *          ]
         */

        $this->room = new \swoole_table(1048576);
        $this->room->column('room_id', \swoole_table::TYPE_INT, 8);
        $this->room->column('admin_user', \swoole_table::TYPE_STRING, 32);
        $this->room->create();


        $this->server->on('Start', [$this, 'onStart']);


        $this->server->on('Connect', [$this, 'onConnect']);

        $this->server->on('Open', [$this, 'onOpen']);

        $this->server->on('Message', [$this, 'onMessage']);

        $this->server->on('Close', [$this, 'onClose']);

        $this->server->on('WorkerStart', [$this, 'onWorkerStart']);

//        $this->server->on('Shutdown', [$this, 'onShutdown']);

        $this->server->start();

//        $output->writeln("WebSocket:start.\n");
//        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }


    public function onStart()
    {
        echo "server is start!\n";
//        parent::onStart(); // TODO: Change the autogenerated stub


    }

    public function onWorkerStart()
    {


    }

    public function onConnect()
    {
        echo "is onConnect\n";

    }


    public function onOpen(\swoole_websocket_server $server, \swoole_http_request $request)
    {
        echo "server:握手成功！用户id：{$request->fd}\n";

        $this->init();

//        $this->time_id = swoole_timer_tick(1000, function () use ($request, $server) {
//            $server->push($request->fd, 'demo');
//        });


        $this->token = $request->get['token'];

        if ($this->redis instanceof Client) {

            $data = explode('__', $this->token);

            if (count($data) == 2) {

                $username = $data[0];

                if ($this->redis->hget($username, 'token') == $this->token) {

                    //存储用户信息
                    $hash = array('fd' => $request->fd, 'online' => true, 'token' => $this->token);

                    $this->redis->hmset($username, $hash);


                    //存储id信息 fd=>user
                    $fd_array = ['username' => $username, 'token' => $this->token];

                    $this->redis->hmset($request->fd, $fd_array);


                    //存进fd到所有用户内存表 fd=>$array
                    if ($this->all_user instanceof \swoole_table) {

                        $array = array('fd' => $request->fd, 'username' => $username, 'token' => $this->token);

                        $this->all_user->set($request->fd, $array);

                    }
                }

            } else unset($data);

            //存储当前id

            //添加id到room1
            $this->redis->hset('room1', $request->fd, $request->fd);

            $room = $this->redis->hkeys('room1');


            //room 循环广播
            foreach ($room as $item) {

                $server->push($item, '新小伙伴' . $request->fd . '加入聊天室');

            }


        } else echo 'redis-error' . __LINE__;

    }


    public function onMessage(\swoole_websocket_server $server, \swoole_websocket_frame $frame)
    {

        //$data 0__$user__$massage      //protect
        //$data 1__$room__$massage      //room
        //$data 2__all_user__$massage  //all_user

        echo "message form {$frame->fd}:{$frame->data},opcode:{$frame->opcode},fin:{$frame->finish}\n";

        $data = explode('__', $frame->data);
        $type = $data[0];
        $id = $data[1];
        $massage = $data[2];
        $fd = $frame->fd;

        switch ($type) {
            //私聊
            case 0:
                if ($this->redis instanceof Client) {

                    $object_fd = $this->redis->hget($id, 'fd');

                    $all_user = TB::getInstance($this->all_user);
                    Db::
                    TB::get()
//                    $all_user->get()

                    $server->push($object_fd, $massage);
                }


                break;
            case 1: //聊天室

            case 2:  //群发

                if ($id == 'all_user') {
                    if ($this->all_user instanceof \swoole_table)
                        foreach ($this->all_user->get())
                }
        }



        if ($this->redis instanceof Client) {

        } else echo 'redis-error' . __LINE__;


//        $server->push($frame->fd, "hello:{$frame->fd},this is server!");


    }

    //指的是客户端关闭
    public function onClose(\swoole_websocket_server $server, $fd)
    {
        echo "client {$fd} closed\n";


        if ($this->redis instanceof Client) {

            $username = $this->redis->hget($fd, 'username');

            //整理user
            $this->redis->hset($username, 'online', false);

            $this->redis->hset($username, 'fd', false);

            //清除fd
            $this->redis->del($fd);

            //从聊天室退出清除fd
            $this->redis->hdel('room1', $fd);

            //广播推出信息

            foreach ($this->all_user as $item) {
                $server->push($item, '小伙伴' . $item['fd'] . '退出聊天室');
            }

//            foreach ($this->redis->hkeys('room1') as $hkey) {
//                $server->push($hkey, '小伙伴' . $fd . '退出聊天室');
//            }
            echo 'clear', $fd;
        } else echo 'redis-error' . __LINE__;


//        if (!empty($this->time_id)) swoole_timer_clear($this->time_id);

    }


}