<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/10 0010
 * Time: 11:20
 */

namespace app\index\controller;

use Swoole\Protocol\WebSocket;
use Swoole;
use think\Controller;

//class Socket extends WebSocket
//{
//    public function onConnect($serv, $fd, $from_id)
//    {
//        parent::onConnect($serv, $fd, $from_id); // TODO: Change the autogenerated stub
//    }
//
//
//    public function onMessage($client_id, $message)
//    {
//        // TODO: Implement onMessage() method.
//    }
//
//    public function onExit($client_id)
//    {
////        parent::onExit($client_id); // TODO: Change the autogenerated stub
//
//        echo $client_id.'退出链接！~';
//    }
//
//    public function onClose($serv, $client_id, $from_id)
//    {
//        parent::onClose($serv, $client_id, $from_id); // TODO: Change the autogenerated stub
//    }
//
//
//    public function onReceive($server, $fd, $from_id, $data)
//    {
//        return parent::onReceive($server, $fd, $from_id, $data); // TODO: Change the autogenerated stub
//    }
//
//
//
//}
//
//$apps = new Socket();
//$apps->loadSetting(__DIR__."/swoole.ini");
//$enable_ssl = false;
//$server = Swoole\Network\Server::autoCreate('0.0.0.0', 9443, $enable_ssl);
//$server->setProtocol($apps);
//$server->run(array());
//class Socket extends Controller
//{
//    public function index()
//    {
//        $serv = new Swoole\Websocket\Server("127.0.0.1", 9502);
//
//        $serv->on('Open', function($server, $req) {
//            echo "connection open: ".$req->fd;
//        });
//
//        $serv->on('Message', function($server, $frame) {
//            echo "message: ".$frame->data;
//            $server->push($frame->fd, json_encode(["hello", "world"]));
//        });
//
//        $serv->on('Close', function($server, $fd) {
//            echo "connection close: ".$fd;
//        });
//
//        $serv->start();
//    }
//}
//
//
//


